name: Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main

permissions:
  contents: read
  packages: write
  # To report GitHub Actions status checks
  statuses: write
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    # if: github.repository == 'azimuth-cloud/ansible-collection-azimuth-ops'

    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          submodules: true

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.4.0

      - name: Load super-linter configuration
        if: always()
        # Use grep inverse matching to exclude eventual comments in the .env file
        # because the GitHub Actions command to set environment variables doesn't
        # support comments.
        # Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
        run: grep -v '^#' super-linter.env >> "$GITHUB_ENV"

      - name: Run super-linter
        # This is a workaround if the ansible-lint step fails
        if: always()
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_CHECKOV: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_ANSIBLE: false
