---
name: Lint 

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main

permissions:
  contents: read
  packages: write
  # To report GitHub Actions status checks
  statuses: write
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    if: github.repository == 'azimuth-cloud/ansible-collection-azimuth-ops'

    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          submodules: true

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.4.0

      - name: Run super-linter
        # This is a workaround if the ansible-lint step fails
        if: always()
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_CHECKOV: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_ANSIBLE: false

  # This job exists so that PRs from outside the main repo are rejected
  fail_on_remote:
    runs-on: ubuntu-latest
    steps:
      - name: PR must be from a branch in the azimuth-cloud/ansible-collection-azimuth-ops repo
        # yamllint disable-line rule:line-length
        run: if [ "${{ github.repository }}" != "azimuth-cloud/ansible-collection-azimuth-ops" ]; then exit 1; fi
